# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d214df751c429c9c740b5a096b687efe5404fbfac1cb41a97ad2483c5e84f3dd0e9f1502936d49b7695cb63a1ab236b7cfb5aa675fd00ede74bc1aa4df97747

test:
  secret_key_base: 993d9bd96c6a1a8c4208bed20ef55d08a5c1357c082b85d9a95f93d6014258a823d6dd0762397cf85ddd4567e7761ff63737f0789da6a10cade9e05661cb9c61

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
